GET http://localhost:3000/api/members/

###
POST http://localhost:3000/api/members
content-type: application/json

{
  "name": "William2",
  "team": "Engineering",
  "position": "Android Developer",
  "emailAddress": "zake@google.com",
  "phoneNumber": "010-xxxx-xxxx",
  "admissionDate": "2018/12/10",
  "birthday": "1995/09/08",
  "profileImage": "profile1.png"
}

###
PUT http://localhost:3000/api/members/3
Content-Type: application/json

{
  "position": "PC Delop123123123er"
}

###
DELETE http://localhost:3000/api/members/12